### ISSUE TITLE
[Meta issue] Projects list issues

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#10045]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Some small bugs in the new UI for project list 

- [x] [The project list <thead> is not reflecting the table data order:](https://github.com/ansible/awx/issues/10029)

![image](https://user-images.githubusercontent.com/12464858/116464922-e9473d00-a842-11eb-97d5-a096b28d8d22.png)

- [x] In the old UI the users can cancel the project sync job running on project list, in the new UI you can only do that from Jobs list

![chrome-capture (6)](https://user-images.githubusercontent.com/12464858/116465170-40e5a880-a843-11eb-9541-d23d4009b0b4.gif)

Suggestion:
![image](https://user-images.githubusercontent.com/12464858/116466637-21e81600-a845-11eb-949e-039d285e5da2.png)

- [ ] [Add credentials data to expanded row](https://github.com/ansible/awx/issues/4023#issuecomment-828689691)
