### ISSUE TITLE
Dependency upgrade Meta Issue

### ISSUE THREAD

**Issue by AlexSCorey** [ansible/awx#10594]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

We should upgrade dependencies.  Below is a list of dependencies that are at least 1 major release behind.  

- [ ] eslint-config-airbnb
- [ ] eslint-plugin-react-hooks
- [ ] has-ansi
- [ ] html entities
- [ ] http-proxy-middleware
- [ ] js-yaml
- [ ] prettier
- [ ] react
- [ ] react-dom
- [ ] styled-components
- [ ] react-router (this will be much easier/faster once the backwards-compat package is available: https://reactrouterdotcom.fly.dev/docs/en/v6/upgrading/v5#backwards-compatibility-package)

Mostly this issue is to discuss which, if any, of these we want to upgrade now, and which can wait.  We should create other issues to track upgrading of individual/groups of dependencies and link those issues to this 1.  

### AWX version

19.2

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

run `npm outdated`

### Expected results

some deps will be outdated

### Actual results

see screen shot below

### Additional information

![Screen Shot 2021-07-06 at 2 14 28 PM](https://user-images.githubusercontent.com/39280967/124647893-89819980-de64-11eb-82f0-9b8b59cce168.png)

**Comment by AlexSCorey** [comment]
We have made really good progress in updating many dependencies that were behind. Some of them were behind by several major releases.  Now, all dependencies have been updated to the latest or are no more than 1 major release behind.  We looked into upgrading React, but with React 18 coming out soon we decided to upgrade react after it is released.

![Screen Shot 2021-08-06 at 1 10 54 PM](https://user-images.githubusercontent.com/39280967/128547522-aa92f339-daa2-4336-adb1-c24e672ae7e6.png)

**Comment by AlexSCorey** [comment]
I've reassigned this to myself to see about updating React to v17 as discussed yesterday during dev sync.

**Comment by AlexSCorey** [comment]
related https://github.com/ansible/awx/issues/11105

**Comment by AlexSCorey** [comment]
I just attempted to upgrade to react 17, but was not successful due to some PF peer dependencies that need React 16.    It seems like if we could get on their  latest versions we could upgrade react but we can't because of this [issue](https://github.com/patternfly/patternfly-react/issues/6421).

**Comment by nixocio** [comment]
React router v6 was released. https://reactrouter.com/docs/en/v6
See also upgrading path https://reactrouter.com/docs/en/v6/upgrading/v5

**Comment by keithjgrant** [comment]
Diving into react-router upgrade now

**Comment by nixocio** [comment]
Create react app can also be upgraded. See: https://github.com/facebook/create-react-app/releases/tag/v5.0.0

**Comment by nixocio** [comment]
```npm outdated``` 02/10/2022

```(base) ➜  ui git:(6f9d4d89cd) npm outdated
Package                             Current   Wanted    Latest  Location                                         Depended by
@babel/core                         7.16.10   7.17.2    7.17.2  node_modules/@babel/core                         ui
@babel/eslint-parser                 7.16.5   7.17.0    7.17.0  node_modules/@babel/eslint-parser                ui
@lingui/cli                          3.8.10   3.13.2    3.13.2  node_modules/@lingui/cli                         ui
@lingui/loader                       3.8.10   3.13.2    3.13.2  node_modules/@lingui/loader                      ui
@lingui/macro                        3.8.10   3.13.2    3.13.2  node_modules/@lingui/macro                       ui
@lingui/react                         3.9.0    3.9.0    3.13.2  node_modules/@lingui/react                       ui
@patternfly/patternfly              4.159.1  4.159.1   4.171.1  node_modules/@patternfly/patternfly              ui
@patternfly/react-core              4.175.4  4.175.4  4.192.15  node_modules/@patternfly/react-core              ui
@patternfly/react-icons              4.26.4   4.26.4   4.43.15  node_modules/@patternfly/react-icons             ui
@patternfly/react-table              4.44.4   4.44.4   4.61.15  node_modules/@patternfly/react-table             ui
@wojtekmaj/enzyme-adapter-react-17    0.6.5    0.6.5     0.6.6  node_modules/@wojtekmaj/enzyme-adapter-react-17  ui
ace-builds                           1.4.12   1.4.14    1.4.14  node_modules/ace-builds                          ui
axios                                0.22.0   0.22.0    0.25.0  node_modules/axios                               ui
codemirror                           5.61.0   5.65.1    5.65.1  node_modules/codemirror                          ui
d3                                    7.1.1    7.1.1     7.3.0  node_modules/d3                                  ui
eslint                                8.7.0    8.8.0     8.8.0  node_modules/eslint                              ui
http-proxy-middleware                 1.3.1    1.3.1     2.0.3  node_modules/http-proxy-middleware               ui
jest-websocket-mock                   2.2.0    2.3.0     2.3.0  node_modules/jest-websocket-mock                 ui
js-yaml                              3.14.1   3.14.1     4.1.0  node_modules/js-yaml                             ui
luxon                                 2.0.1    2.3.0     2.3.0  node_modules/luxon                               ui
mock-socket                           9.0.3    9.1.2     9.1.2  node_modules/mock-socket                         ui
prettier                              2.3.2    2.3.2     2.5.1  node_modules/prettier                            ui
prop-types                           15.7.2   15.8.1    15.8.1  node_modules/prop-types                          ui
react-ace                             9.4.0    9.5.0     9.5.0  node_modules/react-ace                           ui
react-error-boundary                  3.1.3    3.1.4     3.1.4  node_modules/react-error-boundary                ui
react-router-dom                      5.2.0    5.3.0     6.2.1  node_modules/react-router-dom                    ui
rrule                                 2.6.4    2.6.4     2.6.8  node_modules/rrule                               ui
sanitize-html                         2.4.0    2.4.0     2.7.0  node_modules/sanitize-html                       ui
styled-components                     5.3.0    5.3.0     5.3.3  node_modules/styled-components                   ui```

**Comment by nixocio** [comment]
We decide as team to follow a different approach for this dependency upgrade process.
