### ISSUE TITLE
[Meta] Multiple API Requests being made when unnecessary

### ISSUE THREAD

**Issue by akus062381** [ansible/awx#10655]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](http://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I am not entitled to status updates or other assurances.

### Summary

Certain places in Tower, where API requests are being sent and received, multiples (duplicates) of requests are being made when unnecessary. See screenshots:

When creating and saving a new schedule only inside of a workflow template:
![image](https://user-images.githubusercontent.com/63685497/125810688-90484bf6-073e-4e43-872b-f7fe8336a961.png)

When creating a new group inside of an inventory:
![image](https://user-images.githubusercontent.com/63685497/125810850-7308bab5-4682-497d-952e-3964eadefbb0.png)

When visiting the details page of a workflow template:
![image](https://user-images.githubusercontent.com/63685497/125809289-4fcc9928-2e49-40ae-8fd7-f34161dbf1b3.png)

### AWX version

4.0

### Installation method

docker for mac

### Modifications

no

### Steps to reproduce

Create a schedule inside a workflow template. When clicking save, take note of API duplicate requests (4 of each) on network tab.

Access details page for a workflow template. Take note of duplicate requests on network tab.

Create a group inside an inventory. When clicking save, take note of API duplicate requests on network tab.

### Expected results

One of each necessary request should be made.

### Actual results

multiples are being received.

**Comment by nixocio** [comment]
Possible related to: https://github.com/ansible/awx/issues/10551

**Comment by akus062381** [comment]
Additional spot:

![image](https://user-images.githubusercontent.com/63685497/140819627-0a6f9813-57f5-4c36-86be-f0d2b2c3254e.png)

**Comment by akus062381** [comment]
![image](https://user-images.githubusercontent.com/63685497/145895775-712cee97-2d08-4055-a129-a12509e0bba5.png)


I found another place where this is happening. This is when i disassociated 2 teams at one time. I confirmed that 3 POST requests are happening per each team.

**Comment by keithjgrant** [comment]
As I dug into this, I discovered that the function to update breadcrumbs is setting state, which causes a re-fetch of the inventory, which triggers more updates/re-fetches in the child components. Basically a few hooks activating each other more times than they should between various components. Fixing this will require some re-thinking how we go about updating breadcrumbs and/or looking for a way to pull the state vars out of that update function.

**Comment by akus062381** [comment]
confirmed as fixed as of 12/20:

Associating a group to a host on the groups tab inside of a host
Associating a team to a user
