### ISSUE TITLE
AWX "meta: reset_connection" issue

### ISSUE THREAD

**Issue by diptajeet** [ansible/awx#11736]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I am facing issue with "meta: reset_connection" while I am performing a reboot of a device. The playbook task waits for the command_timeout & eventually fails.

The same playbook works fine when ran via native Ansible. So I'd expect its not an issue with the playbook.

What is the best way to make the play wait while a reboot is being performed inside AWX?

### AWX version

17.1.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

docker on linux

### Modifications

no

### Ansible version

2.11.8

### Operating system

CentOS 8

### Web browser

Chrome

### Steps to reproduce

- name: Reload
  hosts: all
  gather_facts: false
  tasks:  
    - name: DEVICE RELOAD | {{ inventory_hostname }} | Reload Device
      cli_command:
        command: reload
        prompt:
            - "[confirm]"
        answer:
            - Y
        vars:
        ansible_command_timeout: 400
    
    - name: DEVICE RELOAD | {{ inventory_hostname }} | Reset the Connection
      meta: reset_connection
    
    - name: DEVICE RELOAD | {{ inventory_hostname }} | Wait 400 Seconds For Device To Reload
      wait_for_connection:
        delay: 30
        connect_timeout: 400

### Expected results

PLAY [Reload] *******************************************************************************************************************************************************

TASK [DEVICE RELOAD | 10.1.1.10 | Reload Device] ********************************************************************************************************************
ok: [10.1.1.10]

TASK [DEVICE RELOAD | 10.1.1.10 | Wait 400 Seconds For Device To Reload] ********************************************************************************************
ok: [10.1.1.10]

### Actual results

PLAY [Reload] *******************************************************************************************************************************************************

TASK [DEVICE RELOAD | 10.1.1.10 | Reload Device] ********************************************************************************************************************
fatal: [10.1.1.10]: FAILED! => {"changed": false, "msg": "command timeout triggered, timeout value is 400 secs.\nSee the timeout setting options in the Network Debug and Troubleshooting Guide."}

### Additional information

Ansible Version 2.11.8

**Comment by shanemcd** [comment]
It looks like you are using an old version of AWX. We do not have the resources to support anything but the latest. Please upgrade.

I'm also not even sure this is an issue with AWX instead of Ansible itself.

If you are still seeing this after a) verifying the same playbook works locally and b) upgrading, please open a new issue.
