### ISSUE TITLE
migration awx 15 > 20 performance degraded

### ISSUE THREAD

**Issue by chris93111** [ansible/awx#11814]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

Hello

We have a scenario where 100 jobs are executed almost at the same time, with awx 15.0.1 in Nomad (hashicorp) it works correctly (4 instances), we try this scenario with awx 20.0.0 and we encounter problems with the controller (4 instances), a good part of the jobs have the following error
**"Task was marked as running but was not present in the job queue, so it has been marked as failed."**

in logs of tasks instance they are only 
2022-02-26 18:56:24,632 DEBUG [f9a90d7126d24eddbca434d72eb8aa23] awx.main.tasks.system job 1571 (failed) is no longer active, reaping orphaned k8s pod
```
2022-02-26 18:56:24,116 DEBUG [f9a90d7126d24eddbca434d72eb8aa23] awx.main.tasks.system Checking for orphaned k8s pods for default-2.
2022-02-26 18:56:24,436 DEBUG [-] awx.main.commands.run_callback_receiver JobEvent.objects.bulk_create(4)
2022-02-26 18:56:24,436 DEBUG [-] awx.main.commands.run_callback_receiver JobEvent.objects.bulk_create(4)
2022-02-26 18:56:24,433 DEBUG [f9a90d7126d24eddbca434d72eb8aa23] awx.main.tasks.system Starting periodic scheduler
2022-02-26 18:56:24,417 DEBUG [f9a90d7126d24eddbca434d72eb8aa23] awx.main.dispatch task 309aca4a-ef0a-496e-b5df-811cd527143c starting awx.main.scheduler.tasks.run_task_manager(*[])
2022-02-26 18:56:24,513 DEBUG [f9a90d7126d24eddbca434d72eb8aa23] awx.main.tasks.system Last scheduler run was: 2022-02-26 18:56:05.473117+00:00
2022-02-26 18:56:24,528 DEBUG [f9a90d7126d24eddbca434d72eb8aa23] awx.main.scheduler Running task manager.
**2022-02-26 18:56:24,632 DEBUG [f9a90d7126d24eddbca434d72eb8aa23] awx.main.tasks.system job 1571 (failed) is no longer active, reaping orphaned k8s pod**
2022-02-26 18:56:24,708 DEBUG [-] awx.main.commands.run_callback_receiver JobEvent.objects.bulk_create(1)
2022-02-26 18:56:24,708 DEBUG [-] awx.main.commands.run_callback_receiver JobEvent.objects.bulk_create(1)
2022-02-26 18:56:24,721 DEBUG [-] awx.main.commands.run_callback_receiver JobEvent.objects.bulk_create(5)
```

```
"job_explanation": "Task was marked as running but was not present in the job queue, so it has been marked as failed.",
    "execution_node": "",
    "controller_node": "awx-cfg-awx-5975c85647-6n84g",
    "result_traceback": "",
    "event_processing_finished": false,
    "work_unit_id": "qknkaeM6",
    "job_template": 176,
    "passwords_needed_to_start": [],
    "allow_simultaneous": true,
    "artifacts": {},
    "scm_revision": "d6db1af4c4c923d10ed914173e60203bb910651d",
    "instance_group": 3,
    "diff_mode": false,
    "job_slice_number": 0,
    "job_slice_count": 1,
    "webhook_service": "",
    "webhook_credential": null,
    "webhook_guid": "",
    "host_status_counts": {},
    "playbook_counts": {
        "play_count": 2,
        "task_count": 46
    },
    "custom_virtualenv": null
    "launch_type": "manual",
    "status": "failed",
    "execution_environment": 3,
    "failed": true,
    "started": "2022-02-26T18:54:15.856010Z",
    "finished": "2022-02-26T18:55:44.569929Z",
    "canceled_on": null,
    "elapsed": 88.714,
```

in EE
```
DEBUG 2022/02/26 18:58:36 Control service closed
DEBUG 2022/02/26 18:58:36 Client disconnected from control service @
ERROR 2022/02/26 18:58:40 Exceeded retries for reading stdout /tmp/receptor/awx-cfg-awx-5975c85647-vdpsw/SVa3Q8yu/stdout
WARNING 2022/02/26 18:58:40 Could not read in control service: read unix /var/run/receptor/receptor.sock->@: use of closed network connection
DEBUG 2022/02/26 18:58:40 Client disconnected from control service @
```

sometime the job are partial output
they are no oom kill in os
7 node in kubernetes with 10 cpu and 16gb memory

there is no cpu or memory saturation
<img width="1357" alt="image" src="https://user-images.githubusercontent.com/27526373/155858004-1b4bf7fd-aa79-4bfa-93c4-d9c64a7ed76a.png">

<img width="1357" alt="image" src="https://user-images.githubusercontent.com/27526373/155858002-af4b1573-c203-4f7e-8df4-0b46b836f987.png">

### AWX version

20.0.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

2.9.9

### Operating system

redhat 8.4

### Web browser

Chrome

### Steps to reproduce

launch 100 job at same time

### Expected results

all job pass 

### Actual results

many job fail with Task was marked as running but was not present in the job queue, so it has been marked as failed

### Additional information

AWX_CONTAINER_GROUP_POD_PENDING_TIMEOUT = "20m"
all instance are capacity to minimal 40 fork

**Comment by chris93111** [comment]
it 's caused by awx_web cpu limitation, I had to increase to 6 cpu limits vs 2 in Nomad with awx 15

<img width="1274" alt="image" src="https://user-images.githubusercontent.com/27526373/155864145-ebf7964f-7e1d-41bf-9ab3-c8a9ab069fbc.png">
