### ISSUE TITLE
AWX Project ignoring branch specification when tracking submodules

### ISSUE THREAD

**Issue by Haagy** [ansible/awx#12293]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Summary

I separated some roles from out main ansible project into single git repositiries. Now I want to include them in AWX by activating the `Track submodules` but get an error (see Actual Result). All of our repositories have `main` branch as their main branch.

Here is my .gitmodules file
```
[submodule "roles/dosomething"]
	path = roles/dosomething
	url = ../roles/dosomething.git
	branch = main
```

### AWX version

21.0.0

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs

### Installation method

kubernetes

### Modifications

no

### Ansible version

core 2.12.5.post0

### Operating system

Rhel 8

### Steps to reproduce

- Add a submodule to a git project and specify a branch different then `master`
- Integrate this project into AWX with `Track submodules` flag activated
- Sync the project

### Expected results

Getting refs from `main` branch

### Actual results

```
{
  "stdout": "Entering 'roles/dosomething'\norigin/master\n",
  "stderr": "fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.\nUse '--' to separate paths from revisions, like this:\n'git <command> [<revision>...] -- [<file>...]'\nfatal: run_command returned non-zero status for roles/dosomething\n.\n",
  "rc": 128,
  "msg": "Unable to determine hashes of submodules",
  "invocation": {
    "module_args": {
      "dest": "/var/lib/awx/projects/_212__ansible_main_0153_pm",
      "repo": "ssh://$encrypted$@gitlab.warburg.com/ansible/ansible-main.git",
      "version": "clean_collections",
      "force": true,
      "track_submodules": true,
      "accept_hostkey": true,
      "remote": "origin",
      "clone": true,
      "update": true,
      "verify_commit": false,
      "gpg_whitelist": [],
      "accept_newhostkey": false,
      "bare": false,
      "recursive": true,
      "single_branch": false,
      "refspec": null,
      "reference": null,
      "depth": null,
      "key_file": null,
      "ssh_opts": null,
      "executable": null,
      "umask": null,
      "archive": null,
      "archive_prefix": null,
      "separate_git_dir": null
    }
  },
  "stdout_lines": [
    "Entering 'roles/dosomething'",
    "origin/master"
  ],
  "stderr_lines": [
    "fatal: ambiguous argument 'origin/master': unknown revision or path not in the working tree.",
    "Use '--' to separate paths from revisions, like this:",
    "'git <command> [<revision>...] -- [<file>...]'",
    "fatal: run_command returned non-zero status for roles/dosomething",
    "."
  ],
  "_ansible_no_log": false,
  "changed": false
}
```

**Comment by AlexSCorey** [comment]
I'm putting needs_triage back on because it was removed, but it looks like no action has been taken here.  I think we should either close this issue, or put it some place to indicate next steps.

**Comment by akus062381** [comment]
This issue should be resolved when the above issue is fixed.
