### ISSUE TITLE
Tracking: AWX code changes for rsyslog decoupling

### ISSUE THREAD

**Issue by relrod** [ansible/awx#13192]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

For the [rsyslog decoupling proposal](https://github.com/ansible/awx/issues/13183) we will need to make some modifications to AWX.

Largely the changes come down to:

- [ ] Write configwatcher daemon that makes use of `construct_rsyslog_conf_template()` when it sees the pg_notify message mentioned above, to write out a new config and restart rsyslog using supervisord
- [ ] In `awx/main/utils/external_logging.py`, change `reconfigure_rsyslog()` to simply send a pg_notify messaage telling the new configwatcher to do its thing

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

N/A

### Current results

N/A

### Sugested feature result

N/A

**Comment by jay-steurer** [comment]
@CFSNM is working on the test coverage for this task as part of a new feature.
