### ISSUE TITLE
Tracking: Image build changes for rsyslog decoupling

### ISSUE THREAD

**Issue by relrod** [ansible/awx#13191]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

We need to modify our current image build process a bit (both for the docker-compose dev env and the kube image) to account for the [rsyslog decoupling proposal](https://github.com/ansible/awx/issues/13183).

- [ ] We need to pull out the rsyslog supervisor configuration section into its own supervisor file (`supervisor_rsyslog.conf` or similar), similar to `supervisor_task.conf`
- [ ] We need a new `launch_awx_rsyslog.sh` added to the container, similar to `launch_awx_task.sh`
- [ ] Later on, once the new daemon exists, it will need to be added to the newly created `supervisor_rsyslog.conf`
- [ ] ... and to `tools/docker-compose/supervisor.conf` for the dev environment

The full completion of this task depends on #13192 being done, but there is some work that can be done before that.

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [X] Other

### Steps to reproduce

N/A

### Current results

N/A

### Sugested feature result

N/A

### Additional information

N/A

**Comment by djyasin** [comment]
PR: https://github.com/ansible/awx/pull/13327
