### ISSUE TITLE
Tracking: Rework websockets to not rely on a shared Redis between task and web instances

### ISSUE THREAD

**Issue by relrod** [ansible/awx#13319]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

This is a tracking issue meant to group together all other issues and PRs related to this work.

Our goal here is to rework our websockets infrastructure to no longer depends on a shared Redis instance between task and web instances, so that task and web can be scaled independently of each other.

We envision that this will be done by fanning messages out from task nodes (where they are generated) to all web nodes who can then forward them on to clients connected to them.

Work is ongoing in the `wsrelay` branch toward this goal.

### Select the relevant components

- [ ] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

N/A

### Current results

Currently a shared Redis instance is required which makes it impossible to scale web and task instances separately.

### Sugested feature result

At this end of this work, we will have decoupled the websockets subsystem of AWX so that a shared Redis instance is no longer required. This will allow users to scale web and task separately.

Messages will emit from task systems like they do currently, and will be fanned out to all web servers who have clients connected to them which have expressed interested in these particular messages. We avoid sending messages to web servers who don't have clients that care about certain messages.
