### ISSUE TITLE
[hop node] documentation for adding hop nodes

### ISSUE THREAD

**Issue by fosterseth** [ansible/awx#14050]
need to extend docs/execution_nodes.md to include hop node info

explain the two ways to link nodes -- `peers` and `peer_from_control_nodes`

things to add: 

```[tasklist]
### Tasks
- [x] update diagram or add a new one that includes a hop node
- [x] section explaining what a hop node is
- [x] section explaining peers_from_control_nodes field
- [x] section explaining the peers field
```
