### ISSUE TITLE
execution node on redhat 7

### ISSUE THREAD

**Issue by bskou57** [ansible/awx#14141]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

Enhancement to Existing Feature

### Feature Summary

Hi

Can I install execution node on redhat 7 ?

thanks

### Select the relevant components

- [X] UI
- [ ] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Steps to reproduce

install execution node on RH7

### Current results

failed

### Sugested feature result

supported install on redhat 7

```[tasklist]
### Tasks
```

**Comment by djyasin** [comment]
Hello @bskou57,
As long as you have the correct Python version, Python 3.9, in the next receptor release or so you should be able to do this. The devel version of the receptor collection may be able to do this now, you can give it a try from there. At this time we do our testing on RHEL 8 or 9.

 In the upcoming release, we are pivoting from using COPR.
