### ISSUE TITLE
Machine credentials wont work for ansible.posix.synchronize 

### ISSUE THREAD

**Issue by gannaramu** [ansible/awx#14291]
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

Hello,

I have been having this issue where ansible awx fails to synchronize from controller node (awx-ee) to remote host while using plain username password Machine Credentials. this functionality was working earlier and is currently broken. I was previously on AWX version 21.5.0 where it used to work fine. but when upgraded to the latest AWX 22.5.0 version this functionality no longer works. after going through the docs I see the following 

> Machine/SSH credentials do not use environment variables. Instead, they pass the username via the ansible -u flag, and interactively write the SSH password when the underlying SSH client prompts for it.

which says awx would interactively write ssh password when prompted. i feel the synchronize step is prompting for credentials and awx is not filling it in.

### AWX version

AWX 22.5.0

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [X] API
- [ ] Docs
- [X] Collection
- [X] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Steps to reproduce

try to synchronize files from control node (AWX-EE) to remote host only using machine credentials (username/password)

### Expected results

sychronize module work fine on the older version.

### Actual results

Synchronize step hangs indefinitely 

```[tasklist]
### Tasks
```

**Comment by fosterseth** [comment]
@gannaramu thanks for opening this issue. can you please provide an example playbook and more detailed steps to reproduce?

**Comment by jceddy** [comment]
My guess is that this has something to do with the limitation mentioned in the Ansible documentation for the synchronize module.

`Currently there are only a few connection types which support synchronize (ssh, paramiko, local, and docker) because a sync strategy has been determined for those connection types. Note that the connection for these must not need a password as rsync itself is making the connection and rsync does not provide us a way to pass a password to the connection.`

I tried to switch to using machine credentials with SSH private key/certificate, and in that case everything else worked fine, but the synchronize call simply failed with no error explanation.

**Comment by jceddy** [comment]
I also had to set sudoer no password privileges for the user on the /usr/bin/rsync command.
