### ISSUE TITLE
Add copy support to all the places

### ISSUE THREAD

**Issue by mabashian** [ansible/awx#4969]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
This can be broken down into smaller pieces but using this as a placeholder so we don't forget.  It's likely that copy will be a repeatable pattern in all the places so may be easy to knock out in one go.
Breaking this out into smaller issues
- [x] Add Copy Support for JT, WFJTs and Credentials #6862 

- [x] Add Copy Support for Projects and Inventories #6863

- [x] Add Copy Support for Inventory Scripts #6864

- [ ] Add Copy Support for Notifications #6865

**Comment by AlexSCorey** [comment]
Breaking this out into smaller PRs.

**Comment by AlexSCorey** [comment]
#6864 and #6865 are blocked until those lists get put in.

**Comment by mabashian** [comment]
Since we have issues for all of the disparate pieces I'm going to close this one.
