### ISSUE TITLE
Convert item lists to Tables

### ISSUE THREAD

**Issue by keithjgrant** [ansible/awx#6189]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY

We've had to do some careful custom CSS to keep the columns aligned in the data lists (e.g. JobsList, etc). In reality, this is tabular data and should probably be converted to use tables.

##### ADDITIONAL INFORMATION

~~PF Tables are not ready to do this yet. The current API is too cumbersome and not worth the work. Blocked by https://github.com/patternfly/patternfly-react/issues/2358 unless we want to roll our own components and copy in PatternFly CSS by hand.~~

All primary lists are converted in devel and pending PRs. Here are secondary lists (e.g. hosts under an inventory) that need to be converted and/or merged with the primary list component:

- [x] Host list under an Inventory
- [x] Team list under a User
- [x] Organization list under User
- [x] Notification list under a Template
- [x] Notification list under a Project
- [x] Notification list under an Organization
- [x] Any component that uses `<OptionsList>`
- [x] Access & Roles under a Team
 - [x] Instance Groups and Related tabs (in progress see https://github.com/ansible/awx/issues/10160)
 - [x] Inventories -> Inventory -> Groups tab -> Group -> Related group tab list and Hosts tab list (in progress https://github.com/ansible/awx/issues/10132)
 - [x] Teams and tabs under teams (in progress https://github.com/ansible/awx/issues/10088)
 - [x] Final search for anywhere remaining using PaginatedDataList that should be converted

**Comment by keithjgrant** [comment]
Patternfly's draft PR on their portion of this work: https://github.com/patternfly/patternfly-react/pull/4950

**Comment by unlikelyzero** [comment]
Please test 
https://github.com/ansible/awx/issues/6300
https://github.com/ansible/awx/issues/7626
https://github.com/ansible/awx/issues/6189
https://github.com/ansible/awx/issues/8086
https://github.com/ansible/awx/issues/7563

**Comment by tiagodread** [comment]
Jobs list covered here ansible/tower-qa#5909

**Comment by unlikelyzero** [comment]
@tiagodread did you test these https://github.com/ansible/awx/issues/6189#issuecomment-744424028

**Comment by akus062381** [comment]
resolved.

**Comment by keithjgrant** [comment]
Reopening. I've got a few more to finish converting before this is all the way completed

**Comment by tiagodread** [comment]
all merged, we can safely close this.
