### ISSUE TITLE
Configure and deploy ansibullbot for ansible/awx. (AWXbot)

### ISSUE THREAD

**Issue by wwitzel3** [ansible/awx#7]
### Summary

The awx project will be using [ansible/ansibullbot](https://github.com/ansible/ansibullbot) to help triage and manage issues and pull requests. We will initially deploy a very limited subset of the bot that is currently being used over on [ansible/ansible](https://github.com/ansible/ansible) and slowly extend it to meet the needs of awx.

### Tasks

- [x] Configure and deploy ansibullbot for the AWX repo.
- [x] Update [CONTRIBUTING.md](https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md) to outline the AWXbot expected behavior.
- [x] Verify AWXbot behavior and deploy against live GH Issues/PRs list.

**Comment by wwitzel3** [comment]
Currently testing behavior against  [wwitzel3/awx](https://github.com/wwitzel3/awx)
