### ISSUE TITLE
[Meta-issue] Advanced Search Issues and RFEs

### ISSUE THREAD

**Issue by unlikelyzero** [ansible/awx#8480]
##### ISSUE TYPE
 - Feature

##### SUMMARY
Note: tagging as Feature on this one so that someone can figure out what's required vs an enhancement based off of what I collected into the meta-issue

There are several advanced search bugs floating around and I collected them for my own sanity

- [ ] [The elements in an advanced search are pushed off screen
The Kebab is triggered by is not used
Z-depth of dropdown for keyfields is not observed. Obscured by modal footer](https://github.com/ansible/awx/issues/7938)
- [ ] [Select All checkbox is out of alignment when Advanced Search selector is enabled](https://github.com/ansible/awx/issues/7825)
- [ ] [Advanced Search on tokens does not function](https://github.com/ansible/awx/issues/8062)
- [x] [Advanced Search on IDs failing](https://github.com/ansible/awx/issues/8477)
- [ ] [Advanced Search for lookups are invalid for certain keys](https://github.com/ansible/awx/issues/7834)
- [x] [Advanced Search Toolbar buttons do not render properly](https://github.com/ansible/awx/issues/8237) (PR up for this currently https://github.com/ansible/awx/pull/8503)
- [ ] [Tweak functionality of Applications List search/sort](https://github.com/ansible/awx/issues/7382)
- [ ] [AWX Smart Inventory Advanced Search issues](https://github.com/ansible/awx/issues/9232)
- [ ] Cannot search for Schedules which are Management Jobs
- [ ] Key variable in advanced search on Host credential modal within Inventory >= Group has no options in drop-down
- [ ] [RFE](https://github.com/ansible/awx/issues/6519) with some [bugs](https://github.com/ansible/awx/issues/6519#issuecomment-795597981)

**Comment by unlikelyzero** [comment]
@AlexSCorey given your recent work on kebabs, can you take a quick look at this tickets to see which are related or solved by your work?

**Comment by AlexSCorey** [comment]
@unlikelyzero I updated this issue, and a few other.  My recent work solves the last item in the list above as noted in the issue.

**Comment by AlexSCorey** [comment]
Removing myself from this issue as I'm not working on it directly.

**Comment by unlikelyzero** [comment]
Feedback from bug bash

- Moving to advanced mode is weird. It is hidden in the “Name” menu/dropdown. The dropdown contains: “Name”, “Advanced” which I find confusing.
- After moving to the Advanced menu, I tried to do some filtering using “or”, “user” and “contains” with some string. Pressing on “search” gives 400 bad request error (see snapshot). I tried several filtering with different modes (or, and) but nothing works.
- After something went wrong, I tried to edit the filter. The “key” dropdown menu doesn’t show the values to choose from anymore. I had to press “clear all filters” to enable the key dropdown to show keys again.

**Comment by unlikelyzero** [comment]
Filed with https://github.com/ansible/awx/issues/8919

**Comment by unlikelyzero** [comment]
@mabashian @jlmitch5 tagging Feature on this one so that someone can figure out what's required vs enhancement based off of what I collected into the meta-issue

**Comment by unlikelyzero** [comment]
closing to track individually
