### ISSUE TITLE
[Meta issue] Credentials bugs

### ISSUE THREAD

**Issue by tiagodread** [ansible/awx#9635]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
While verifying https://github.com/ansible/awx/pull/9368 I've found a couple of things happening on devel:

- [x] 1. Using external secret management system display the component Ace editor wrong
![image](https://user-images.githubusercontent.com/12464858/111816196-50c0b300-88bb-11eb-9097-a3d90d22903c.png)

**Steps to reproduce:**

1. Create a credential `CyberArk Conjur Secret Lookup` 
2. Create a credential for AWS using the CyberArk on **Secret Key** as an external secret management system

- [x] 2. Trying to edit the credential replacing the external secret for a pain text and saving:
![chrome-capture (2)](https://user-images.githubusercontent.com/12464858/111816825-0ee43c80-88bc-11eb-9623-5e8e952e60e9.gif)

**Steps to reproduce:**
See the gif.

- [x] 3. ~All types with `Verify SSL` option is being displayed as enabled on the form and details~

![chrome-capture (3)](https://user-images.githubusercontent.com/12464858/111817668-0b9d8080-88bd-11eb-93ac-2649e2a76b8a.gif)

**Types:**
- Tower
- CyberArk AIM Central Credential Provider Lookup
- OpenShift or Kubernetes API Bearer Token
- OpenStack

**Comment by mabashian** [comment]
3 is a duplicate of #9955 and will be fixed by https://github.com/ansible/awx/pull/9960

**Comment by tiagodread** [comment]
> 3 is a duplicate of #9955 and will be fixed by #9960

Fixed by #9960

**Comment by akus062381** [comment]
4/29/2021- for Bullet point 1 above, it appears that this problem has not yet been addressed.
![image](https://user-images.githubusercontent.com/63685497/116566179-88684500-a8d4-11eb-9169-943695912793.png)

**Comment by tiagodread** [comment]
@mabashian while verifing this issue I found this:

1. Create a credential CyberArk Conjur Secret Lookup
2. Create a credential CyberArk AIM Central Credential Provider Lookup
3. Create an AWS credential using the CyberArk Conjur Secret Lookup on Secret Key as an external secret management system
3. Edit this AWS credential and select CyberArk AIM Central Credential Provider Lookup  as an external secret management system
4. save the AWS credential

Result:
![image](https://user-images.githubusercontent.com/12464858/117365698-11175000-ae96-11eb-8eae-fffa37f1d786.png)

**Comment by akus062381** [comment]
@mabashian Update on this issue:
Issues 1 and 2 are fixed and good to go. 
Issue 3 is still happening except for the Ansible Tower credential type.

**Comment by mabashian** [comment]
@akus062381 I think you may be referring to the fact that `Verify SSL` is checked by default on the add form for a handful of credential types.  This is by design.  The API indicates to us that the `default` value for those fields is `true` so we check the checkbox in the add form.  Editing the credential seems to correctly check/uncheck that box:

![openstack](https://user-images.githubusercontent.com/9889020/118326485-0894ca00-b4d3-11eb-8fe4-d45530171451.gif)

If I'm misunderstanding send over some reproduction steps and I'll take another look.

**Comment by akus062381** [comment]
this is all set.
